# Generated by Django 4.2 on 2023-04-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_filetransfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileTnsfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="screenshots/")),
                ("file", models.FileField(upload_to="file/")),
            ],
        ),
        migrations.DeleteModel(
            name="FileTransfer",
        ),
        migrations.AddField(
            model_name="nanoiot",
            name="what",
            field=models.TextField(default="custom_cmd", max_length=100),
        ),
        migrations.AddField(
            model_name="nanoiot",
            name="where",
            field=models.CharField(default="emb", max_length=100),
        ),
    ]
