# Generated by Django 4.2 on 2023-04-21 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0006_nanoiot_image_alter_filetransfer_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileTransfer",
        ),
    ]
