# Generated by Django 4.2 on 2023-04-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0007_delete_filetransfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nanoiot",
            name="what",
            field=models.TextField(default="cusm_cmd", max_length=100),
        ),
    ]
