# Generated by Django 4.2 on 2023-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0008_alter_nanoiot_what"),
    ]

    operations = [
        migrations.AddField(
            model_name="nanoiot",
            name="do_it",
            field=models.BooleanField(default=False),
        ),
    ]
