# Generated by Django 4.2 on 2023-04-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0009_nanoiot_do_it"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nanoiot",
            name="do_it",
        ),
    ]
