# Generated by Django 4.2 on 2023-04-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0010_remove_nanoiot_do_it"),
    ]

    operations = [
        migrations.AddField(
            model_name="nanoiot",
            name="dashboard_link",
            field=models.CharField(
                default="http://10.106.134.210:8080/d/lpU4hW3Mz/dashboard-montage2?orgId=1&refresh=1m&kiosk",
                max_length=255,
            ),
        ),
    ]
