# Generated by Django 4.2 on 2023-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0011_nanoiot_dashboard_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="nanoiot",
            name="existence",
            field=models.BooleanField(default=False),
        ),
    ]
