# Generated by Django 4.2 on 2023-04-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0012_nanoiot_existence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nanoiot",
            name="existence",
        ),
    ]
