# Generated by Django 4.2 on 2023-04-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0013_remove_nanoiot_existence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nanoiot",
            name="where",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emboutissage", "emboutissage"),
                    ("ferrage", "ferrage"),
                    ("montage", "montage"),
                    ("peinture", "peinture"),
                    ("o2x", "o2x"),
                    ("moteur", "moteur"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
