# Generated by Django 4.2 on 2023-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0014_alter_nanoiot_where"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nanoiot",
            name="where",
            field=models.CharField(
                choices=[
                    ("emboutissage", "emboutissage"),
                    ("ferrage", "ferrage"),
                    ("montage", "montage"),
                    ("peinture", "peinture"),
                    ("o2x", "o2x"),
                    ("moteur", "moteur"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
