# Generated by Django 4.2 on 2023-04-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0017_remove_nanoiot_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nanoiot",
            old_name="screenshot<django.db.models.fields.CharField>.png",
            new_name="image",
        ),
    ]
