# Generated by Django 4.2 on 2023-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "API",
            "0018_rename_screenshot_django_db_models_fields_charfield_png_nanoiot_image",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="nanoiot",
            name="resolution",
            field=models.CharField(
                choices=[("screenshot", "screenshot"), ("upgrade", "upgrade")],
                default=("1920x1080", "1920x1080"),
                max_length=20,
            ),
        ),
    ]
