# Generated by Django 4.2 on 2023-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0019_nanoiot_resolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nanoiot",
            name="resolution",
            field=models.CharField(
                choices=[("screenshot", "screenshot"), ("upgrade", "upgrade")],
                default="1920x1080",
                max_length=20,
            ),
        ),
    ]
