# Generated by Django 4.2 on 2023-05-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0023_nanoiot_reset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nanoiot",
            name="reset",
        ),
        migrations.RemoveField(
            model_name="nanoiot",
            name="video_link",
        ),
    ]
