# Generated by Django 4.2 on 2023-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0024_remove_nanoiot_reset_remove_nanoiot_video_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="nanoiot",
            name="code",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
