# Generated by Django 4.2 on 2023-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0025_nanoiot_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="nanoiot",
            name="video",
            field=models.FileField(null=True, upload_to="videos/"),
        ),
    ]
