# Generated by Django 4.2 on 2023-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0027_alter_nanoiot_resolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nanoiot",
            name="hostname",
            field=models.CharField(
                default="dm",
                max_length=100,
                unique=True,
                verbose_name="NanoIoT's Hostname",
            ),
        ),
        migrations.AlterField(
            model_name="nanoiot",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="nanoiot",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="nanoiot",
            name="where",
            field=models.CharField(
                choices=[
                    ("emboutissage", "emboutissage"),
                    ("ferrage", "ferrage"),
                    ("montage", "montage"),
                    ("peinture", "peinture"),
                    ("o2x", "o2x"),
                    ("moteur", "moteur"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="NanoIoT's Location",
            ),
        ),
    ]
