# Generated by Django 4.2 on 2023-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0029_nanoiot_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="nanoiot",
            name="time",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
